### ISSUE TITLE
disable-organization-admin-account arguments use Unicode dashes instead of ASCII

### ISSUE THREAD

**Issue by bmorrissirromb** [awsdocs/amazon-guardduty-user-guide#23]
Currently:
`aws guardduty disable-organization-admin-account ‐‐admin-account-id "123456789012"`

Should be:
`aws guardduty disable-organization-admin-account --admin-account-id "123456789012"`

I realize these look identical to the eye, but the difference causes the command not to recognize the parameter name.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
