### ISSUE TITLE
ProxyCommand not working in sample_findings.md

### ISSUE THREAD

**Issue by mlaruskiaws** [awsdocs/amazon-guardduty-user-guide#26]
The ProxyCommand used for connecting to the tester instance no longer works with the instances created via CloudFormation. ProxyCommand with NetCat results in an error. Using the "-W" switch with OpenSSH corrects the issue.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
