### ISSUE TITLE
Improving the organization of current and archived finding types

### ISSUE THREAD

**Issue by Gaianab** [awsdocs/amazon-guardduty-user-guide#7]
I would appreciate any ideas on how to better structure and present a rather large list of GuardDuty finding types. Some (the majority) are current. Some are archived. The archived ones might become current at some point. New types will be added in months and years to come. The list is expected to grow. Having it all in one topic is not longer the best or most readable/user-friendly option. 

I would love to hear your thoughts and ideas.

**Comment by ghost** [comment]
i scraped them into a CSV - https://github.com/lindy64/aws-guardduty

**Comment by randalld-aws** [comment]
thanks for your help with this
